// gelu_luts.h -- AUTO-GENERATED by gen_luts.py.  DO NOT EDIT BY HAND.
//   regenerate with:  python gen_luts.py
// Gemma-4-E2B MLP: folded GELU table G' (Q3.13, exact) + fast-inverse
// magic seeds (rsqrt mode drives the post_feedforward RMSNorm).
// Plain C types on purpose: shared by MLP.cpp, tb_MLP.cpp and host.cpp.
#ifndef GELU_LUTS_H
#define GELU_LUTS_H

// quantization points (PLACEHOLDER values until the real QAT scale
// export is ready -- see gen_luts.py header)
static const double MLP_S_G = 0.0625;  // gate_proj.output_activation_scale
static const double MLP_S_U = 0.0625;  // up_proj.output_activation_scale
static const double MLP_S_H = 0.25;  // down_proj.input_activation_scale

#define MLP_GLUT_FRAC 13   // G' is Q3.13
#define MLP_RQ_SHIFT  20   // SRQ multipliers r_g/r_u: raw * 2^-20
#define MLP_CD_SHIFT  24   // c_down dequant scales:   raw * 2^-24
#define MLP_LN_FRAC   13   // layernorm (1+gamma):     raw * 2^-13
#define MLP_HID_FRAC  8    // hidden / residual / output: Q7.8
#define MLP_LN_EPS    9.5367431640625e-07  // 2^-20, RMSNorm epsilon

// I_y = MAGIC - (I_x >> s):  s=0 for 1/x, s=1 for 1/sqrt(x) (RMSNorm)
static const unsigned int FASTINV_MAGIC_RECIP = 0x7EF477D5U; // 2129950677
static const unsigned int FASTINV_MAGIC_RSQRT = 0x5F3759E0U; // 1597463008

// G'[q_g + 128] = rne( GELU_tanh(q_g*S_G) * S_U / S_H * 2^13 ), Q3.13.
// Folds dequant -> GELU -> rescale-to-S_H into one EXACT 256-entry ROM.
static const short GELU_LUT_Q313[256] = {
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,      0,      0,      0,
         0,      0,      0,      0,      0,     -1,     -1,     -1,
        -1,     -2,     -2,     -3,     -3,     -4,     -5,     -6,
        -7,     -9,    -11,    -13,    -16,    -19,    -22,    -26,
       -31,    -36,    -42,    -48,    -56,    -64,    -73,    -82,
       -93,   -104,   -117,   -130,   -144,   -158,   -174,   -189,
      -206,   -222,   -239,   -255,   -271,   -286,   -301,   -314,
      -325,   -335,   -342,   -347,   -348,   -346,   -341,   -331,
      -316,   -296,   -272,   -241,   -205,   -163,   -115,    -61,
         0,     67,    141,    221,    307,    399,    496,    600,
       708,    821,    939,   1062,   1188,   1317,   1450,   1585,
      1723,   1862,   2003,   2146,   2289,   2433,   2577,   2722,
      2866,   3011,   3154,   3298,   3440,   3582,   3723,   3864,
      4003,   4142,   4279,   4416,   4552,   4688,   4822,   4956,
      5089,   5222,   5354,   5485,   5616,   5747,   5877,   6007,
      6137,   6266,   6395,   6524,   6653,   6781,   6910,   7038,
      7167,   7295,   7423,   7551,   7680,   7808,   7936,   8064,
      8192,   8320,   8448,   8576,   8704,   8832,   8960,   9088,
      9216,   9344,   9472,   9600,   9728,   9856,   9984,  10112,
     10240,  10368,  10496,  10624,  10752,  10880,  11008,  11136,
     11264,  11392,  11520,  11648,  11776,  11904,  12032,  12160,
     12288,  12416,  12544,  12672,  12800,  12928,  13056,  13184,
     13312,  13440,  13568,  13696,  13824,  13952,  14080,  14208,
     14336,  14464,  14592,  14720,  14848,  14976,  15104,  15232,
     15360,  15488,  15616,  15744,  15872,  16000,  16128,  16256
};

#endif // GELU_LUTS_H
