// gelu_luts.h -- AUTO-GENERATED by gen_luts.py.  DO NOT EDIT BY HAND.
//   regenerate with:  python gen_luts.py --layer-dir mlp_bin_output/layer_15
// Gemma-4-E2B MLP, layer 15: folded GELU table G' (Q4.12, exact) and
// the activation scales of the QAT checkpoint (per-tensor, float32).
// Plain C types on purpose: shared by MLP.cpp, tb_MLP.cpp and host.cpp.
#ifndef GELU_LUTS_H
#define GELU_LUTS_H

#define MLP_LAYER_IDX 15   // checkpoint layer the tables below belong to

// quantization points, read from activation_scales.json of the export
static const double MLP_S_IN  = 0.023188970983028412;  // gate_proj/up_proj.input_activation_scale (x_q grid)
static const double MLP_S_G   = 0.030511820688843727;  // gate_proj.output_activation_scale
static const double MLP_S_U   = 0.030511820688843727;  // up_proj.output_activation_scale
static const double MLP_S_H   = 0.02005414292216301;  // down_proj.input_activation_scale
static const double MLP_S_Y   = 0.0081057418137788773;  // down_proj.output_activation_scale
static const double MLP_S_Y16 = 3.1663053960073739e-05;  // S_Y / 256: grid of the INT16 output y_q

#define MLP_GLUT_FRAC 12   // G' is Q4.12 (auto: peak |G'| = 5.8955)
#define MLP_RQ_SHIFT  20   // SRQ multipliers r_g/r_u:  raw * 2^-20
#define MLP_CD_SHIFT  24   // c_down requant multiplier: raw * 2^-24

// G'[q_g + 128] = rne( GELU_tanh(q_g*S_G) * S_U / S_H * 2^MLP_GLUT_FRAC ).
// Folds dequant -> GELU -> rescale-to-S_H into one EXACT 256-entry ROM.
static const short GELU_LUT_I16[256] = {
        -1,     -1,     -1,     -1,     -1,     -1,     -2,     -2,
        -2,     -2,     -3,     -3,     -3,     -4,     -4,     -5,
        -5,     -6,     -7,     -7,     -8,     -9,    -10,    -12,
       -13,    -14,    -16,    -17,    -19,    -21,    -23,    -26,
       -28,    -31,    -34,    -37,    -41,    -45,    -49,    -53,
       -58,    -63,    -68,    -74,    -80,    -87,    -94,   -101,
      -109,   -117,   -126,   -135,   -145,   -156,   -167,   -178,
      -190,   -203,   -216,   -230,   -245,   -260,   -276,   -292,
      -309,   -327,   -345,   -364,   -383,   -403,   -424,   -445,
      -467,   -489,   -511,   -534,   -558,   -582,   -606,   -630,
      -654,   -679,   -703,   -728,   -752,   -776,   -800,   -824,
      -847,   -869,   -891,   -912,   -932,   -951,   -969,   -986,
     -1001,  -1015,  -1028,  -1038,  -1047,  -1053,  -1058,  -1060,
     -1059,  -1056,  -1050,  -1042,  -1030,  -1016,   -998,   -976,
      -951,   -923,   -891,   -855,   -815,   -771,   -723,   -671,
      -614,   -553,   -488,   -418,   -343,   -264,   -181,    -93,
         0,     97,    199,    306,    417,    533,    653,    778,
       907,   1041,   1179,   1321,   1467,   1617,   1771,   1929,
      2091,   2256,   2425,   2597,   2773,   2951,   3133,   3317,
      3504,   3694,   3886,   4081,   4278,   4476,   4677,   4879,
      5083,   5289,   5496,   5704,   5913,   6123,   6335,   6547,
      6759,   6972,   7186,   7400,   7614,   7829,   8044,   8258,
      8473,   8687,   8902,   9116,   9330,   9543,   9757,   9969,
     10182,  10393,  10605,  10815,  11026,  11235,  11444,  11653,
     11860,  12068,  12274,  12480,  12685,  12890,  13094,  13298,
     13500,  13703,  13904,  14105,  14306,  14506,  14706,  14905,
     15103,  15301,  15499,  15696,  15892,  16089,  16285,  16480,
     16675,  16870,  17065,  17259,  17453,  17646,  17840,  18033,
     18226,  18419,  18611,  18803,  18996,  19188,  19379,  19571,
     19763,  19954,  20145,  20337,  20528,  20719,  20910,  21101,
     21291,  21482,  21673,  21863,  22054,  22244,  22435,  22625,
     22816,  23006,  23197,  23387,  23577,  23767,  23958,  24148
};

#endif // GELU_LUTS_H
